services:
  - type: static
    name: soltropy-dashboard
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production

